Add prediction script and accordion ui
demid5111/arxiv-ai-search pull request #10
Opened 2023-12-05 00:03 UTC by SalnikovIgor

2023-12-05 04:35 UTC, demid5111 requested changes

2023-12-05 04:35 UTC, demid5111 commented on vector_db/app/database.py
> +        chroma_client = chromadb.PersistentClient(path='C:\\Users\\admin\\arxiv-ai-search\\vector_db\\chroma')
.

2023-12-05 04:35 UTC, demid5111 commented on vector_db/app/database.py
>          )
newline

2023-12-05 04:35 UTC, demid5111 commented on vector_db/scripts/prediction.py
> +
nl

2023-12-05 04:35 UTC, demid5111 commented on vector_db/static/js/main.js
> +    // resultsBox.replaceChildren();
rm

2023-12-05 04:35 UTC, demid5111 commented on vector_db/templates/index.html
>  </html>
nl

2023-12-05 04:35 UTC, demid5111 commented on result.csv
rm from git, put in dist and ignore it

2023-12-05 04:35 UTC, demid5111 commented on vector_db/scripts/prediction.py
> +    embedding = model.embedding(abstract)
should be done via chroma

2023-12-05 04:35 UTC, demid5111 commented on vector_db/scripts/prediction.py
> +for row in df_google['query_article_link']:
should be easy to iterate through rows

2023-12-05 04:35 UTC, demid5111 commented on vector_db/scripts/prediction.py
> +df_google = df_google.dropna()
we also drop items that include non-indexed papers

2023-12-05 04:35 UTC, demid5111 commented on vector_db/scripts/prediction.py
> +    results = db.query_embedding(embedding)
we make cosine similarity search?

2023-12-05 04:35 UTC, demid5111 commented on vector_db/scripts/prediction.py
> +    df.loc[len(df)] = [full_row['_url'].values[0]] + [item['url'] for item in results['metadatas'][0]]
use append

2023-12-05 19:53 UTC, SalnikovIgor commented on vector_db/scripts/prediction.py
> +    embedding = model.embedding(abstract)
Chroma use  only `all-MiniLM-L6-v2`

2023-12-06 09:36 UTC, demid5111 requested changes

2023-12-06 09:36 UTC, demid5111 commented on vector_db/charts/all_years.png
rm

2023-12-06 09:36 UTC, demid5111 commented on vector_db/README.md
> +
4?

2023-12-06 13:25 UTC, merged